name: Build PR

on:
    pull_request:
        branches:
            - master

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.300
    - name: Log dotnet info
      run: dotnet --info
    - name: Run test
      run: ./build.ps1 --target=Test
